### ISSUE TITLE
Slower ARM binary - CMake seems to default to debug on ARM

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#115]
Since packJPG and packMP3 fixes, precomp speed has dropped a lot.

I didn't test all the algorithms but at least the deflate part takes about 2.25x to complete, lzma compression takes exactly 2x and brunsli 3.7x.

This is a comparison between two different ARM versions only (before and after the fixes) - I didn't test other O.S. and platforms.

**Comment by schnaader** [comment]
Guess I've got the culprit, seems I was too optimistic with the CMake release default flag, doesn't seem to work (at least on ARM?). Can you check the size of the precomp executable using `ls -l`? Here, when just using `cmake ./` instead of `cmake ./ -DCMAKE_BUILD_TYPE=Release`, it still did a debug build with a size of 12 MB. Using the latter produced a 2.2 MB binary that compressed much faster.

**Comment by M-Gonzalo** [comment]
You're right. I can't believe I didn't notice I was working with a 5x bigger exe 🤦🏼‍♂️

**Comment by schnaader** [comment]
After some tests with CMake on Linux x64 and ARM x64, it seems that CMake indeed defaults to debug builds on ARM. I'll make some changes to the CMake script to more reliable generate a release and generate a warning if release is disabled so this will be more obvious.

**Comment by schnaader** [comment]
CMake will now warn, if the build type is not "Release". Otherwise, it will output "Build type: Release", so seeing this will confirm that debug build type is disabled. Note that even with the warning, CMake will continue to not break things like the MSVC build.
