### ISSUE TITLE
Memory management / avoiding temporary files

### ISSUE THREAD

**Issue by schnaader** [schnaader/precomp-cpp#14]
At the moment, everything is done using temporary files, so even very small streams are processed on disk instead of memory which slows down Precomp a lot. On the other hand, it allows handling of very large streams that are several GB in size.

Proposal: There should be a parameter to set a max. memory size, everything up to that size will be processed in memory and only if more memory is needed, streams are processed on disk using temporary files.

**Comment by kassane** [comment]
Hello, how are you?
I tested your project being developed and realized a large accumulation of memory leak.
After some tests with files with an average of 2GB each, there was a bug due to lack of precompilation processing, this means failed continued to point to abort without error or exception.

RAM:6GB

The parameters used were:(-intense -v -cn)

**Comment by schnaader** [comment]
2 temporary files removed for partial matches by [commit faa477](https://github.com/schnaader/precomp-cpp/commit/faa4776346a03d2d432b6a9825700b25902f613c)

**Comment by schnaader** [comment]
Version 0.4.6 release uses temporary files only in these cases:
  - streams are bigger than 64 MB
  - multi PNG stitching
  - bZip2
  - GIF
  - recursion

I probably won't target any of them except recursion, so I close this issue for now.
