### ISSUE TITLE
precomp crashes on this file

### ISSUE THREAD

**Issue by StephanBusch** [schnaader/precomp-cpp#52]
latest precomp 0.4.6 crashes on this file every time:

[http://www.squeezechart.com/KTv1.apk](url)

**Comment by schnaader** [comment]
Further investigation shows these are actually 2 bugs, a MP3 parsing bug and slow JPG parsing (see issue #5 )

The MP3 parsing bug leads to the crash - not only in the 0.4.6 development versions, also in older release versions like 0.4.5. There's a ZIP stream 1 048 576 bytes long and at the end (position 1 036 663), a MP3 frame of length 12520 is detected - this exceeds the stream length as 1036663+12520 > 1048576, so it should be discarded instead of being processed.

When disabling MP3, the slow JPG parsing occurs at the end of the file (position 36 733 053) - this is another 1048576 bytes long ZIP stream that is full of SOI marker headers (0xFFD8) without actually containing JPG streams. There are 29102 occurences of the hex string 0xFFD8FF that triggers JPG parsing.

**Comment by schnaader** [comment]
File doesn't lead to a crash anymore and is processed in under a minute.
