### ISSUE TITLE
Changes for macOS

### ISSUE THREAD

**Issue by maki-chan** [schnaader/precomp-cpp#60]
Hi,

I wanted to push the precomp application to the macOS homebrew manager (https://brew.sh) and opened a pull request there. There are some changes though that would have to be made and that can only be fixed upstream in this repository. You can look at the pull request here: https://github.com/Homebrew/homebrew-core/pull/15562

First of all, the Unix Makefile would need an install target (that should be easy to do, it just needs to install the built precomp binary to a suitable location). It would be needed to have it done via a variable in the Makefile, so the brew formula can override the variable and install the application to the correct folder automatically.

Secondly, the main Makefile uses the `-s` flag which is not available on OS X Yosemite and thus, precomp would not be supported on all platforms that are still served by brew (El Capitan and Sierra ignore this flag, but Yosemite does not compile with it at all). Is this flag really needed? According to GCC, it is supposed to "Remove all symbol table and relocation information from the executable."

The other two requested changes from the pull request have to be changed by me in the formula, though. So there is nothing, you would need to change.

**Comment by Diazonium** [comment]
IIRC the -s flag means "strip away all unnecessary stuff from the binary", so pretty much the only thing it does is reduce the size.

**Comment by schnaader** [comment]
First of all: Since I didn't do any development on macOS, take everything I say with a grain of salt.

About the Makefiles: I've considered using multiple Makefiles (e.g. something like Makefile.linux32 for a 32-bit linux compile) that can be used with "make -f". Since OSX does require at least two changes, it would make sense to add a Makefile.osx for it. For the first iteration, a simple copy/paste and adjusting of the existing Makefiles would be legit, and there should be some way to reduce the redundancy in the long run.

Generally, I don't have much spare time at the moment since I'm in an exam phase at the university. So I don't know how much I'll be able to do or how fast. Feel free to send pull requests with OSX related changes though, this might be the fastest way to proceed.

**Comment by schnaader** [comment]
Thanks for the Makefile, added it to the master branch and added `$(PREFIX)` as requested in #68
