### ISSUE TITLE
Lepton image compression

### ISSUE THREAD

**Issue by pasha-zzz** [schnaader/precomp-cpp#67]
I saw enhancement about FLIF image compression. But its for lossless images. There are Lepton compression from Dropbox. It offers bit identical compression-decompression of JPEG with 22% gain.
https://github.com/dropbox/lepton

**Comment by schnaader** [comment]
Precomp already uses [PackJPG](https://github.com/packjpg/packJPG) for lossless compression of JPG files. Lepton is similar (it is based on uncmpJPG by packJPG's author) and gives similar compression ratios. Testing the JPG file from issue #24:

`Original file: 4,307,553 bytes`
`Lepton v1.2: 3,395,557 bytes, 2.4 s`
`PackJPG v2.5j: 3,415,122 bytes, 4.8 s`
`Precomp v0.4.6: 3,292,325 bytes, 3.5 s`
`paq8px_v112 -3: 3,076,748 bytes, 109 s`

Lepton is faster because it's using multi-threading. Precomp compresses this particular file a bit better than packJPG because it also compresses the thumbnail it contains. [paq8px](https://github.com/hxim/paq8px) has a more advanced JPG compression and gives even better results, but it's very slow.

Since I already have plans to do multi-threading too, Lepton doesn't give big advantages over packJPG.
