### ISSUE TITLE
Precomp crashes on this file

### ISSUE THREAD

**Issue by StephanBusch** [schnaader/precomp-cpp#73]
Precomp crashes on this file:

https://drive.google.com/file/d/1mYaC_ajUzf4Y-MgPRsHOWcWYil1K74iz/view?usp=sharing

Can you please check that?

**Comment by schnaader** [comment]
Just to be sure I've got the same file:

833,776,296 bytes, md5sum 97ae5f6b8c8ba3e58ba86313c3e5bd7c

**Comment by StephanBusch** [comment]
yes, that's the same file.
I was using Precomp 0.4.6 built on 12th of march 2017 since this is the latest x64 executable I have.
I used it with -cn switch, so no -intense or -brute switches were used.
Where can I get Precomp 0.4.7 x64?

**Comment by schnaader** [comment]
Oh, that's a quite old development version you are using. The [official 0.4.6 release](https://github.com/schnaader/precomp-cpp/releases) doesn't crash on this file anymore (the crash comes from a MP3 parsing error, by the way) and has many fixes and speed improvements, so you should use it instead of the old version.

Regarding speed, compare the old version with the official version on your file (using -t-3 for the old one to avoid the MP3 crash):
  - Old dev version, -cn -t-3:
    - 6 min 2 s
  - Official 0.4.6, -cn:
    - 4 min 30 s

There's no official 0.4.7 release yet, just a development version for testers. Development versions have to be build from the latest git commit, here's the current Windows x64 version:
[precomp_047_dev_commit_e77daaf_win64.zip](https://github.com/schnaader/precomp-cpp/files/1524601/precomp_047_dev_commit_e77daaf_win64.zip)
