### ISSUE TITLE
Crash during GIF handling

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#94]
There is nothing much more to add. Problematic images attached.
[GIFs.zip](https://github.com/schnaader/precomp-cpp/files/2766838/GIFs.zip)

**Comment by M-Gonzalo** [comment]
Yes. 

I'm using Ubuntu 18.04.1 LTS.
The version of precomp is the latest commit here on github compiled with gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
I have an Intel Atom if it's worth noticing.

```
$time precomp -cn -v SavingTabsFinal.gif 

Precomp v0.4.7 Unix 64-bit - DEVELOPMENT version - USE FOR TESTING ONLY
Free for non-commercial use - Copyright 2006-2018 by Christian Schneider
  preflate v0.3.5 support - Copyright 2018 by Dirk Steinke

Input file: SavingTabsFinal.gif
Output file: SavingTabsFinal.pcf

Using packJPG for JPG recompression, packMP3 for MP3 recompression.
--> packJPG library v2.5k (01/22/2016) by Matthias Stirner / Se <--
--> packMP3 library v1.0g (01/22/2016) by Matthias Stirner <--
More about packJPG and packMP3 here: http://www.matthiasstirner.com

(0.00%) Possible GIF found at position 0
Segmentation fault (core dumped)

real	0m5,336s
user	0m0,688s
sys	0m0,377s
```

**Comment by schnaader** [comment]
Still no success in reproducing, tried the same setup (Ubuntu 18.04.1 LTS, gcc 7.3.0) both on a cloud instance (Intel Xeon) and a local VM, both succeed instead of crashing, regardless of command-line parameters (tried none, "-cn" and "-cn -v"). The file SavingTabsFinal.gif can be decompressed to 212,706,761 bytes, but recompression fails. No crashes so far, I'll keep on trying though.

Giflib could be updated, yes. though I'm not sure if it'd help in this case, most GIF errors so far were errors on Precomp's side. Also, GIF recompression in general could need a revision, e.g. the PAQ implementation seperately processes frames instead of the whole file at once so partial success is still possible on "exotic"/optimized GIF files.

**Comment by M-Gonzalo** [comment]
So, what do we do? I tried recompiling just in case last time gcc was in another version, but still got the crash. I didn't use any custom options for the compiler.
Perhaps, if you're about to update giflib / refurbish the whole thing, I can try again after the changes...

BTW, maybe this belong to another issue, but, would it be too much work to write a generic parser to all LZW streams, lie the one for deflate? I mean, the algorithm is in place right now...

Thanks in advance!

**Comment by schnaader** [comment]
You could try both samba and SavingTabsFinal.gif with "-cn -t-f" (-t-f disables GIF) and see if the crash goes away. If it still crashes for one of the files or both, something else is wrong, too.

**Comment by M-Gonzalo** [comment]
There was the problem. Now all three gifs and all silesia are processed OK using -t-f. I wonder how it didn't occur to me earlier to try.
Anyway, all recent updates to giflib have been bug fixes, so chances are just by updating it precomp gets fixed too. Because it seems to be a rare thing this crash, appearing only under very specific circumstances.

**Comment by schnaader** [comment]
Could reproduce the crash now - silly mistake, didn't set the CMake release flag for the Ubuntu builds. So debug build works, but release doesn't work (at least on Ubuntu, Windows MSVC release builds work). Will investigate this further.

**Comment by schnaader** [comment]
A final remark: Updating GifLib wouldn't help here as this is GIF-handling code outside GifLib. Might be a good idea to upgrade anyway, of course.
